import keyMirror from "keymirror";

const ActionTypes = keyMirror({
  GAME_FORTUNE_WHEEL_USER_BET_X2: null,
  GAME_FORTUNE_WHEEL_USER_BET_X3: null,
  GAME_FORTUNE_WHEEL_USER_BET_X5: null,
  GAME_FORTUNE_WHEEL_USER_BET_X50: null,
  GAME_FORTUNE_WHEEL_ROUND_BEGIN: null,
  GAME_FORTUNE_WHEEL_ROUND_DRAW: null,
  GAME_FORTUNE_WHEEL_USER_BET: null,
  GAME_FORTUNE_WHEEL_BETS_CLOSED: null,
  GAME_FORTUNE_WHEEL_STATUS: null,
  GAME_FORTUNE_WHEEL_ROOM_JOIN: null,
  GAME_FORTUNE_WHEEL_ROOM_LEAVE: null,
});

export default ActionTypes;
